### ISSUE TITLE
Doesnt wwork anymore :(

### ISSUE THREAD

**Issue by jamajamajaaama** [jryz101/Translate-WordPress-Slider-Revolution#1]
This trick doesnt work anymore unfortunately

**Comment by jryz101** [comment]
I'm using this solution a couple of days ago and it works for me.

**Comment by jamajamajaaama** [comment]
Did it showed also the Language options for each slide?

**Comment by jryz101** [comment]
Yes! Check out my screenshot.
![Screen Shot 2020-08-14 at 2 08 21 AM](https://user-images.githubusercontent.com/23055114/90170963-5d37d700-ddd3-11ea-8a9d-a0674e98f10e.png)

**Comment by jamajamajaaama** [comment]
Interesting. I added the same code in functions.php and under the Slide WPML button did not show up. Under General it showed.

**Comment by jryz101** [comment]
Please make sure you follow this guide: https://wpml.org/documentation/plugins-compatibility/creating-multilingual-sliders-with-revolution-slider-and-wpml/ to set up the slider translation setting correctly. It should be working.😃

**Comment by jamajamajaaama** [comment]
I did it already, but I made a workaround by creating multiple sliders and then included them depending on language selection at frontend.
