### ISSUE TITLE
Ciritical error

### ISSUE THREAD

**Issue by MHULT** [jryz101/Translate-WordPress-Slider-Revolution#2]
Hey,

Found this addon but can't get it working.
I copy the code to my function.php and when reloading everything I just get the critical error when entering the Slider Revolution. And I've got Polylang installed.

Slider Revolution version: 6.5.7

Thanks!

**Comment by jryz101** [comment]
Can you show me what is the error message? Thank you.

**Comment by MHULT** [comment]
Ett kritiskt fel har uppstått på webbplatsen. Kolla inkorgen för webbplatsens administratörs e-post för vidare instruktioner.
Läs mer om felsökning i WordPress.

This is the only message that appears which is In Swedish. It says "A critical error has occurred on the website. Check your inbox for the administration e-mail address for further information".

This is the only lines I've got in my functions.php

`<?php
function my_theme_enqueue_styles() { 
    wp_enqueue_style( 'parent-style', get_template_directory_uri() . '/style.css' );
}
add_action( 'wp_enqueue_scripts', 'my_theme_enqueue_styles' );


if ( function_exists('pll_languages_list') ) { 
	add_action('wpml_loaded', '__return_true', 10, 0);
	do_action('wpml_loaded');
}

`

**Comment by jryz101** [comment]
You can enable the debug mode to learn more about the error.
